# 서버 설정 -> 포트 8080, 인코딩 정보
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error: # 시큐리티에서 throw 한 Exception e 출력을 위함.
    include-message: always
    include-binding-errors: always

cloud:
  aws:
    s3:
      bucket: demoim-img
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
---
spring:
  profiles:
    include:
      - aws
  h2:
    console:
      enabled: true
---
spring:
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false


